name: Docker-pipeline..

trigger:
- master
- feature/*

pool:
  name: CI-agent 

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: Build
    steps:
    - task: CmdLine@2
      displayName: Install docker and set permissions
      inputs:
        script: 'curl -fsSL https://get.docker.com -o get-docker.sh && chmod u+x get-docker.sh && ./get-docker.sh && sudo chmod 666 /var/run/docker.sock && sudo chown ubuntu:docker /var/run/docker.sock'

    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'docker-connection'
        repository: 'containeridanho555'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

# Continuous Deployment Process for Staging Environment
- stage: DeployToStaging
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  variables:
    - gorup: "Staging-variables"
  jobs:
  - deployment: staging
    displayName: Deploy to Staging
    environment:
      name: staging
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - template: templates/docker-cd-template.yaml
          
# Continuous Delivery Process for Production Environment
- stage: DeployToProduction
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  variables:
    - gorup: "Production-variables"
  jobs:
   - deployment: production
     displayName: Deploy to Production
     environment:
       name: production
       resourceType: VirtualMachine
     strategy:
       runOnce:
         deploy:
           steps:
             - template: templates/docker-cd-template.yaml